### ISSUE TITLE
Offhand bottle broken with /b toggle thrown

### ISSUE THREAD

**Issue by Luexa** [jwkerr/XPManager#2]
When you have `/b toggle thrown` off set so you consume bottle directly, if you have bottle in offhand you get the correct XP but it consumes item in mainhand instead of consuming bottle from offhand. This can be a big problem as not only does it dupe XP, but it can also consume a tool from mainhand that you are trying to mend (I lost my maxed netherite pickaxe from this, but you can take advantage of the dupe if you have dirt or something in your mainhand).

**Comment by jwkerr** [comment]
i'll fix this in a second

**Comment by jwkerr** [comment]
should be fixed in 5750719
